version: "3.9"
services:
  web:
    build: .
    ports:
      - "8012:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - FLASK_ENV=development

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: kesehatan_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
